svc_totp_manage:
  path: /manage/
  controller: Svc\TotpBundle\Controller\TotpController::manageTotp

svc_totp_qrcode:
  path: /qrcode/
  controller: Svc\TotpBundle\Controller\TotpController::totpQRCode

svc_totp_enable:
  path: /enable/
  controller: Svc\TotpBundle\Controller\TotpController::enableTotp

svc_totp_disable:
  path: /disable/
  controller: Svc\TotpBundle\Controller\TotpController::disableTotp

svc_totp_oth_disable:
  path: /disable/{id}
  controller: Svc\TotpBundle\Controller\TotpController::disableOtherTotp

svc_totp_cleartd:
  path: /cleartd/
  controller: Svc\TotpBundle\Controller\TotpController::clearTrustedDevice

svc_totp_clear_oth_td:
  path: /clearotd/{id}
  controller: Svc\TotpBundle\Controller\TotpController::clearOtherTrustedDevice

svc_totp_user_admin:
  path: //admin/users/
  controller: Svc\TotpBundle\Controller\TotpAdminController::index

svc_totp_forgot:
  path: /forgot/
  controller: Svc\TotpBundle\Controller\TotpForgotController::forgetPassword

svc_totp_verify_forgot:
  path: /forgot/verify/
  controller: Svc\TotpBundle\Controller\TotpForgotController::verifyForgetPassword

svc_totp_forgot_btn:
  path: /forgot/btn/
  controller: Svc\TotpBundle\Controller\TotpController::forgotButton
