services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Svc\TotpBundle\Controller\TotpController:
  Svc\TotpBundle\Controller\TotpAdminController:
  Svc\TotpBundle\Controller\TotpForgotController:

  Svc\TotpBundle\Service\TotpLogger:
    arguments:
      - "@Svc\\TotpBundle\\Service\\TotpDefaultLogger"
      - "%kernel.environment%"
    public: true


  Svc\TotpBundle\Service\TotpDefaultLogger:
    public: true

  Svc\TotpBundle\Controller\MfaCrudController:
